version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${PROJECT_NAME}Rabbitmq
    #    ports:
    #      - 5672:5672
    #      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq

  web:
    build: ./main_backend
    container_name: ${PROJECT_NAME}Web
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
      - images_to_render:/app/media/images
      - rendered_nft:/app/staticfiles/img-tracking/data/nft
    networks:
      - rabbitmq
      - nginx
    depends_on:
      - rabbitmq

  generator:
    build: ./generator
    container_name: ${PROJECT_NAME}Generator
    volumes:
      - images_to_render:/app/main_backend_images
      - rendered_nft:/app/output
    networks:
      - rabbitmq
    depends_on:
      - web
      - rabbitmq

  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}Nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - staticfiles:/app/static
      - mediafiles:/app/media
      - rendered_nft:/app/static/img-tracking/data/nft
    depends_on:
      - web
    networks:
      - nginx


networks:
  rabbitmq:
    driver: bridge
    name: ${PROJECT_NAME}RabbitmqNetwork
  nginx:
    driver: bridge
    name: ${PROJECT_NAME}NginxNetwork


volumes:
  staticfiles:
    name: ${PROJECT_NAME}Staticfiles

  mediafiles:
    name: ${PROJECT_NAME}Mediafiles

  images_to_render:
    name: ${PROJECT_NAME}ImagesToRender

  rendered_nft:
    name: ${PROJECT_NAME}RenderedNFTMarkers
