version: "3.7"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./staticfiles:/app/static
    depends_on:
      - web
