# Generated by Django 3.1.7 on 2021-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar',
            name='image',
            field=models.ImageField(upload_to='img-tracking/data/images/'),
        ),
    ]
