# Generated by Django 3.1.7 on 2021-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0002_auto_20210321_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ar',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
